modLoader="javafml"
loaderVersion="[36,)"
license="Not specified"

[[mods]]
modId="arinium"
version="3.0.0"
displayName="Arinium"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Nasakyuu"

[[dependencies.arinium]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




